language: node_js

node_js:
  - '8'

cache:
  directories:
    - ~/.npm

env:
  global:
    - FORCE_COLOR=1

jobs:
  include:
    - stage: test
      script:
        - npm run prettier
        - npm run lint
        - npm run build
        - npm test
        - node_modules/.bin/nyc report --reporter=json
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      script:
        - npm run build
        - npm run release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  only:
    - master
